name: Lint on pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  full_ci:
    runs-on: ubuntu-18.04
    steps:
      # Checkout code
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install Node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: eslint
      uses: icrawl/action-eslint@v1
      